# Generated by Django 5.1.6 on 2025-02-19 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BreathingTechnique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='BreathingPhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Inhale', 'Inhale'), ('Hold', 'Hold'), ('Exhale', 'Exhale')], max_length=50)),
                ('duration', models.PositiveIntegerField(help_text='Duration in seconds')),
                ('technique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='home.breathingtechnique')),
            ],
        ),
    ]
