# Generated by Django 5.1.6 on 2025-02-26 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_breathingtechnique_hold_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='breathingtechnique',
            name='hold_time',
        ),
        migrations.AddField(
            model_name='breathingtechnique',
            name='in_hold_time',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='breathingtechnique',
            name='out_hold_time',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
